### ISSUE TITLE
Rest endpoints?

### ISSUE THREAD

**Issue by BaileyMillerSSI** [MicrosoftDocs/xbox-live-docs#11]
There is a brief mention of the rest API and then nothing about how to use it or links to further reading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35407bb-abe9-c32e-d3db-130457903c01
* Version Independent ID: f4e29f8f-ead3-c6e0-bb33-9f026005a86a
* Content: [Introduction to Xbox Live APIs - Xbox Live](https://docs.microsoft.com/en-us/gaming/xbox-live/introduction-to-xbox-live-apis#feedback)
* Content Source: [xbox-live-docs-pr/introduction-to-xbox-live-apis.md](https://github.com/MicrosoftDocs/xbox-live-docs/blob/docs/xbox-live-docs-pr/introduction-to-xbox-live-apis.md)
* Product: **xboxlive**
* GitHub Login: @aablackm
* Microsoft Alias: **aablackm**

**Comment by cjm91** [comment]
Any further update on this?

**Comment by p0358** [comment]
https://docs.microsoft.com/en-us/gaming/xbox-live/xbox-live-rest/uri/atoc-xboxlivews-reference-uris

**Comment by BaileyMillerSSI** [comment]
> https://docs.microsoft.com/en-us/gaming/xbox-live/xbox-live-rest/uri/atoc-xboxlivews-reference-uris

I am getting a 404 for this

**Comment by p0358** [comment]
@BaileyMillerSSI they must had changed URLs, even the one at the top of the issue's description does not work anymore...

**Comment by kavika13** [comment]
The link is working for me, no 404.
