### ISSUE TITLE
Samples for ID@Xbox GitHub repo lead to 404 page

### ISSUE THREAD

**Issue by cookie966507** [MicrosoftDocs/xbox-live-docs#27]
This link above: https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/ID%40XboxSDK does not resolve and leads to a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54caca7d-5467-6e26-0655-94755bb6d454
* Version Independent ID: af2eb388-bdab-5639-2775-2dae5fa874d9
* Content: [Xbox Live resources, sites, and downloads - Xbox Live](https://docs.microsoft.com/en-us/gaming/xbox-live/xbox-live-resources#feedback)
* Content Source: [xbox-live-docs-pr/xbox-live-resources.md](https://github.com/MicrosoftDocs/xbox-live-docs/blob/docs/xbox-live-docs-pr/xbox-live-resources.md)
* Product: **xboxlive**
* GitHub Login: @aablackm
* Microsoft Alias: **aablackm**

**Comment by mlamaute** [comment]
Links have been fixed
