### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by Bersekael** [MicrosoftDocs/xbox-live-docs#45]
Xbox Dev Store... page not found
Getting Started with Xbox One Development ... page not found

great job there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ed0026-c3f2-65dd-6534-ffab9ed904fb
* Version Independent ID: 7b228331-1813-5492-200f-2fb832f8682a
* Content: [Testing on the Xbox One console - Xbox Live](https://docs.microsoft.com/en-us/gaming/xbox-live/testing-on-console)
* Content Source: [xbox-live-docs-pr/testing-on-console.md](https://github.com/MicrosoftDocs/xbox-live-docs/blob/docs/xbox-live-docs-pr/testing-on-console.md)
* Product: **xboxlive**
* GitHub Login: @aablackm
* Microsoft Alias: **aablackm**

**Comment by mlamaute** [comment]
Hi - these links appear to be working when I tested them. Are you a managed partner who is still unable to access the links? If so, do you know how to reach your MS contact?

All the best,
Miriam

**Comment by Bersekael** [comment]
yes, thank you, they restored it later
